### ISSUE TITLE
Obtaining Teamraiser data using client-side API

### ISSUE THREAD

**Issue by cfern87** [noahcooper/luminateExtend#73]
Hello there again!

First, thank you again for all of your help with the API support that you've provided. I'ts been stellar.

I'm unclear, however, on the implications of your resolution of my most recent issue: https://github.com/noahcooper/luminateExtend/issues/72

I can attempt to infer that this means one of the following: 

* I do not need any login to retrieve Teamraiser data - this doesn't seem likely given the screenshot attached when I attempt to call "getTeamPage." 
![2015-03-16_17h36_09](https://cloud.githubusercontent.com/assets/11179641/6677489/e30d518c-cc06-11e4-8472-b8ad202a4dc4.png)

* I cannot use the API Admin account, but I will need another Admin account which isn't an ADMIN API account (unsure how to set this up as I do not have direct access to the backend, but my contact probably does)
* I should login with a regular users' account. (waiting to hear back from my contact to set this up)
* There are more restrictions than the luminateAPI documentation alludes to about client-side API calls (if this is the case, could you please clarify).

Can you please clarify what you mean? I've minimal experience with the luminate API, but a fair amount of experience with web dev in general. That being said, I'm not clear on the what types of accounts can do what for client vs server-side api calls, and what's required in each case, and I'd like to provide clear information to my server administrator.

If you visit http://dev-t4p.skytemple.com/luminate/index.html and click the "click here" link at the bottom you can see the code that I am attempting to run. Some potentially useful information:

* fr_ID = 1750
* I am using an API key, which has been verified as the proper API key. 
* link in the luminate API library for getTeamPageInfo: http://open.convio.com/api/#teamraiser_api.getTeamPageInfo_method.html

**Comment by cfern87** [comment]
I just attempted to connect with a user with the following constituent record. I'm receiving the same error. 
![screen shot 2015-03-11 at 9 36 52 am](https://cloud.githubusercontent.com/assets/11179641/6677619/23f091a4-cc08-11e4-8e2e-caa81a8cb845.png)



Seems like I'm missing something here...

**Comment by noahcooper** [comment]
Gotcha!

First let me explain how authentication works for the server- vs. client-side Luminate Online API. When calling the server-side API (say using some PHP code written to pull data from Luminate Online into a third-party CMS like Wordpress), requests must be made from a whitelisted IP address (i.e. the IP address of the server where Wordpress is hosted), and must be signed with a username and password for an "API Administrator". This is really just a special kind of constituent record created in the back-end of Luminate Online, given access to some subset of functions based on which Administrative Groups the record is placed in (e.g. one API Admin could be given permission to [refund](http://open.convio.com/api/#donation_api.refundTransaction_method.html) transactions, while another might be limited to [creating and updating constituent records](http://open.convio.com/api/#constituent_api.createOrUpdate_method.html)). With the server-side API, this additional level of authentication is required due to the fact that some methods expose data and functionality that otherwise would only be available to an administrator from the organization within the admin UI of the application (like refunding transactions as mentioned previously -- obviously you wouldn't want anyone to be able to do that!).

The client-side API is different. By default, the client-side API makes requests in the context of an anonymous user, and requires no authentication whatsoever. This is because many of the client-side API methods simply expose data and functionality that is otherwise already available to an average site visitor (e.g. [searching for nearby TeamRaiser events](http://open.convio.com/api/#teamraiser_api.getTeamraisersByDistance_method.html) by ZIP radius or [making a donation](http://open.convio.com/api/#donation_api.donate_method.html)), so no security is needed. Some methods, however, expose personal information about a user, like their [name, address, phone number, and email address](http://open.convio.com/api/#constituent_api.getUser_method.html), or their [participation in an organization's TeamRaiser events](http://open.convio.com/api/#teamraiser_api.getRegistration_method.html). Such methods are denoted in the documentation on http://open.convio.com with the word "Yes" under the "Requires Authentication" heading for the method. Unlike the server-side API, client-side API calls which require authentication are not signed with a username and password. Instead, they are signed with an authentication token, which can be retrieved at any time after the user has logged in. When using luminateExtend, this is as simple as passing `requiresAuth: true` to `luminateExtend.api`, e.g.

``` js
luminateExtend.api({
  api: 'cons', 
  data: 'method=getUser', 
  requiresAuth: true, 
  requestType: 'POST', 
  callback: function(response) {
    console.log(response);
  }
});
```

Again, this call is made in the context of an individual user after they have logged in, not an API Admin -- no admin credentials are required. 

Looking at your code, am I correct that your goal is to retrieve a list of teams that have registered for the "Tips for Parkinson's 2015"? If so, getTeamPageInfo is not the method you're after -- that method is used to retrieve the personalized HTML content and photo for a single team's page on the website, and can only be called by the team captain of that team. To get a list of teams, you'd want to use the [getTeamsByInfo](http://open.convio.com/api/#teamraiser_api.getTeamsByInfo_method.html) method. Again, since this method exposes information that's otherwise available to a site visitor, it can be called in an anonymous context, and requires no authentication token.

``` js
luminateExtend.api({
  api: 'teamraiser', 
  data: 'method=getTeamsByInfo&fr_id=1750', 
  callback: function(response) {
    var teams = luminateExtend.utils.ensureArray(response.getTeamSearchByInfoResponse.team);
    $.each(teams, function() {
      console.log(this);
    });
  }
});
```

If you'd like to see a real world example, check out the search for a team feature on the JDRF One Walk website at https://www2.jdrf.org/site/SPageServer/?pagename=walk_participant_search. The pertinent JavaScript can be found at line 244 of https://www2.jdrf.org/jdrf-framework/js/global/main.js.
